WebCoreOne/Controllers/PAdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebCoreOne.Models;
using WebCoreOne.Models.Context;
using WebCoreOne.Repositories;
using WebCoreOne.ViewModels.PAdmin;
using WebCoreOne.ViewModels.Role;
using WebCoreOne.ViewModels.SiteSetting;

namespace WebCoreOne.Controllers
{
    [Authorize(policy: "DynamicRole")]
   // [Authorize(Roles = "ادمین")]
    public class PAdminController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly AppDbContext _dbContex;
        private readonly IMemoryCache _memoryCache;
        private readonly IUtilities _utilities;
      

        public PAdminController(RoleManager<IdentityRole> roleManager,
                                UserManager<IdentityUser> userManager,
                                AppDbContext dbContext,
                                IMemoryCache memoryCache,
                                IUtilities utilities)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _dbContex = dbContext;
            _memoryCache = memoryCache;
            _utilities = utilities;

        }




        ////////////////////////////////{  Index  }//////////////////////////////////


        public IActionResult Index()
        {
            return View();
        }

        ////////////////////////////////{  Role  }//////////////////////////////////


        public IActionResult Roles()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }


        [HttpGet]
        public IActionResult AddRole()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRole(string name)
        {
            if (string.IsNullOrEmpty(name)) return NotFound();
            var role = new IdentityRole(name);
            var result = await _roleManager.CreateAsync(role);
            if (result.Succeeded) return RedirectToAction("Roles");

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            return View(role);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            await _roleManager.DeleteAsync(role);

            return RedirectToAction("Roles");
        }


        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();

            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRole(string id, string name)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(name)) return NotFound();

            var role = await _roleManager.FindByIdAsync(id);
            if (role == null) return NotFound();
            role.Name = name;
            var res = await _roleManager.UpdateAsync(role);
            if (res.Succeeded) return RedirectToAction("Roles");

            foreach (var error in res.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(role);
        }

        ////////////////////////////////{ User in Role  }//////////////////////////////////


        public IActionResult Users()
        {
            var model = _userManager.Users
                .Select(u => new IndexViewModel()
                { Id = u.Id, UserName = u.UserName, Email = u.Email }).ToList();
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(string id, string name)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(name)) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            user.UserName = name;
            var res = await _userManager.UpdateAsync(user);
            if (res.Succeeded) return RedirectToAction("Users");

            foreach (var error in res.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> AddUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.ToList();
            var model = new AddUserToRoleViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (!await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRolres.Add(new UserRoleViewModel()
                    {
                        RoleName = role.Name
                    });
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUserToRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();

            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();

            var reqRol = model.UserRolres.Where(r => r.IsSelected)
                .Select(u => u.RoleName).ToList();

            var res = await _userManager.AddToRolesAsync(user, reqRol);
            if (res.Succeeded) return RedirectToAction("Users");

            foreach (var error in res.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> RemoveUserToRole(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            var roles = _roleManager.Roles.ToList();
            var model = new AddUserToRoleViewModel() { UserId = id };

            foreach (var role in roles)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.UserRolres.Add(new UserRoleViewModel()
                    {
                        RoleName = role.Name
                    });
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserToRole(AddUserToRoleViewModel model)
        {
            if (model == null) return NotFound();

            var user = await _userManager.FindByIdAsync(model.UserId);
            if (user == null) return NotFound();

            var reqRol = model.UserRolres.Where(r => r.IsSelected)
                .Select(u => u.RoleName).ToList();

            var res = await _userManager.RemoveFromRolesAsync(user, reqRol);
            if (res.Succeeded) return RedirectToAction("Users");

            foreach (var error in res.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUser(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            await _userManager.DeleteAsync(user);

            return RedirectToAction("Users");

        }

        [HttpGet]
        public async Task<IActionResult> UpdateSecurityStamp(string id)
        {
            if (string.IsNullOrEmpty(id)) return NotFound();
            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();
            await _userManager.UpdateSecurityStampAsync(user);
            return RedirectToAction("Users");
        }

        ////////////////////////////////{ Site settinge  }//////////////////////////////////


        public IActionResult settings()
        {
            var model = _dbContex.siteSettings.ToList();
            return View(model);
        }

        [HttpGet]
        public IActionResult RoleValidatioGuid()
        {
            var RoleValidatioGuidSite = _dbContex.siteSettings.FirstOrDefault(t => t.Key == "RoleValidationGuid");

            var model = new RoleValidatioGuidViewModel()
            {
                Value = RoleValidatioGuidSite?.Value,
                LastTimeChanged = RoleValidatioGuidSite?.LastTimeChanged
            };

            return View(model);
        }


        [HttpPost]
        public IActionResult RoleValidatioGuid(RoleValidatioGuidViewModel model)
        {

WebCoreOne/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCoreOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebCoreOne</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-lg-grow-1 ml-auto">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li>
                                <form asp-controller="Account" asp-action="LogOut" method="post">
                                    <button type="submit" class="btn nav-link text-dark">خروج</button>
                                </form>
                            </li>
                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">ورود</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">عضویت</a>
                            </li>
                        }

                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (User.IsInRole("testadmin"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PAdmin" asp-action="Index">Panel Admin</a>
                            </li>

                        }

                        @if (User.IsInRole("testadmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="pageOne">Page One</a>
                            </li>
                        }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1399 - WebCoreOne - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>